# Generated by Django 5.1.5 on 2025-01-25 17:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Erecord', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Edetails',
            new_name='EmployeeDetail',
        ),
    ]
